
source('getParameters.R')
source('Check_Identifiable_vs2.R')
source('getParms_noAge.R')
source('load_data_seasons.R')
source('run_agebased_model_true_Catch.R')
source('plotUncertainty.R')
source('getSelec.R')
source('create_TMB_data.R')
source('getRefpoint_biomass.R')
source('Check_Identifiable_vs2.R')
source('getF.R')
source('getRefpoint.R')