## Load the required scripts and packages 
require(TMB)
#library(TMBdebug)
require(ggplot2)
source('plotValues.R')
source('getUncertainty.R')
source('load_data.R')
source('ylimits.R')
source('getParameters.R')
source('Check_Identifiable_vs2.R')
#source('getParms_noAge.R')