
source('R/getParameters.R')
source('R/getParameters_OM.R')
source('R/Check_Identifiable_vs2.R')
#source('getParms_noAge.R')
source('R/load_data_seasons.R')
source('R/run_agebased_model_true_Catch.R')
source('R/plotUncertainty.R')
source('R/getSelec.R')
source('R/create_TMB_data.R')
#source('getRefpoint_biomass.R')
source('R/Check_Identifiable_vs2.R')
source('R/getF.R')
source('R/run_multiple_MSEs.R')
source('R/getRefpoint.R')